### ISSUE TITLE
update default branch name from master to main

### ISSUE THREAD

**Issue by SundayTyper** [BackStoryOrg/website#14]
Recent(ish) changes to suggested practices state that the default branch of a project should now be called 'main' rather than 'master' due to negative historical connotations. 

In the same vein as any clusters set up with 'master' and 'slave' nodes

**Comment by rendall** [comment]
The `master` in the `master` branch is the connotation of "something to be referred to" as in _master copy_ and not _master/slave_.  Changing it will be a PITA.  So, no.
